interface Continenti {
  [key: string]: string
}

export const continenti: Continenti =  { // see https://gist.github.com/nobuti/3816985
  AF: 'asia', // "Islamic Republic of Afghanistan")
  AX: 'europa', // "Åland Islands")
  AL: 'europa', // "Republic of Albania")
  DZ: 'africa', // "People's Democratic Republic of Algeria")
  AS: 'oceania', // "American Samoa")
  AD: 'europa', // "Principality of Andorra")
  AO: 'africa', // "Republic of Angola")
  AI: 'america settentrionale', // "Anguilla")
  AQ: 'Antarctica', // "Antarctica (the territory South of 60 deg S)")
  AG: 'america settentrionale', // "Antigua and Barbuda")
  AR: 'america meridionale', // "Argentine Republic")
  AM: 'asia', // "Republic of Armenia")
  AW: 'america settentrionale', // "Aruba")
  AU: 'oceania', // "Commonwealth of Australia")
  AT: 'europa', // "Republic of Austria")
  AZ: 'asia', // "Republic of Azerbaijan")
  BS: 'america settentrionale', // "Commonwealth of the Bahamas")
  BH: 'asia', // "Kingdom of Bahrain")
  BD: 'asia', // "People's Republic of Bangladesh")
  BB: 'america settentrionale', // "Barbados")
  BY: 'europa', // "Republic of Belarus")
  BE: 'europa', // "Kingdom of Belgium")
  BZ: 'america settentrionale', // "Belize")
  BJ: 'africa', // "Republic of Benin")
  BM: 'america settentrionale', // "Bermuda")
  BT: 'asia', // "Kingdom of Bhutan")
  BO: 'america meridionale', // "Plurinational State of Bolivia")
  BQ: 'america settentrionale', // '535'
  BA: 'europa', // "Bosnia and Herzegovina")
  BW: 'africa', // "Republic of Botswana")
  BV: 'Antarctica', // "Bouvet Island (Bouvetoya)")
  BR: 'america meridionale', // "Federative Republic of Brazil")
  IO: 'asia', // "British Indian Ocean Territory (Chagos Archipelago)")
  VG: 'america settentrionale', // "British Virgin Islands")
  BN: 'asia', // "Brunei Darussalam")
  BG: 'europa', // "Republic of Bulgaria")
  BF: 'africa', // "Burkina Faso")
  BI: 'africa', // "Republic of Burundi")
  KH: 'asia', // "Kingdom of Cambodia")
  CM: 'africa', // "Republic of Cameroon")
  CA: 'america settentrionale', // "Canada")
  CV: 'africa', // "Republic of Cape Verde")
  KY: 'america settentrionale', // "Cayman Islands")
  CF: 'africa', // "Central african Republic")
  TD: 'africa', // "Republic of Chad")
  CL: 'america meridionale', // "Republic of Chile")
  CN: 'asia', // "People's Republic of China")
  CX: 'asia', // "Christmas Island")
  CC: 'asia', // "Cocos (Keeling) Islands")
  CO: 'america meridionale', // "Republic of Colombia")
  KM: 'africa', // "Union of the Comoros")
  CD: 'africa', // "Democratic Republic of the Congo")
  CG: 'africa', // "Republic of the Congo")
  CK: 'oceania', // "Cook Islands")
  CR: 'america settentrionale', // "Republic of Costa Rica")
  CI: 'africa', // "Republic of Cote d'Ivoire")
  HR: 'europa', // "Republic of Croatia")
  CU: 'america settentrionale', // "Republic of Cuba")
  CW: 'america settentrionale', // "Curaçao")
  CY: 'asia', // "Republic of Cyprus")
  CZ: 'europa', // "Czech Republic")
  DK: 'europa', // "Kingdom of Denmark")
  DJ: 'africa', // "Republic of Djibouti")
  DM: 'america settentrionale', // "Commonwealth of Dominica")
  DO: 'america settentrionale', // "Dominican Republic")
  EC: 'america meridionale', // "Republic of Ecuador")
  EG: 'africa', // "Arab Republic of Egypt")
  SV: 'america settentrionale', // "Republic of El Salvador")
  GQ: 'africa', // "Republic of Equatorial Guinea")
  ER: 'africa', // "State of Eritrea")
  EE: 'europa', // "Republic of Estonia")
  ET: 'africa', // "Federal Democratic Republic of Ethiopia")
  FO: 'europa', // "Faroe Islands")
  FK: 'america meridionale', // "Falkland Islands (Malvinas)")
  FJ: 'oceania', // "Republic of Fiji")
  FI: 'europa', // "Republic of Finland")
  FR: 'europa', // "French Republic")
  GF: 'europa', // "French Guiana")
  PF: 'europa', // "French Polynesia")
  TF: 'Antarctica', // "French Southern Territories")
  GA: 'africa', // "Gabonese Republic")
  GM: 'africa', // "Republic of the Gambia")
  GE: 'asia', // "Georgia")
  DE: 'europa', // "Federal Republic of Germany")
  GH: 'africa', // "Republic of Ghana")
  GI: 'europa', // "Gibraltar")
  GR: 'europa', // "Hellenic Republic Greece")
  GL: 'europa', // "Greenland")
  GD: 'america settentrionale', // "Grenada")
  GP: 'america settentrionale', // "Guadeloupe")
  GU: 'oceania', // "Guam")
  GT: 'america settentrionale', // "Republic of Guatemala")
  GG: 'europa', // "Bailiwick of Guernsey")
  GN: 'africa', // "Republic of Guinea")
  GW: 'africa', // "Republic of Guinea-Bissau")
  GY: 'america meridionale', // "Co-operative Republic of Guyana")
  HT: 'america settentrionale', // "Republic of Haiti")
  HM: 'Antarctica', // "Heard Island and McDonald Islands")
  VA: 'europa', // "Holy See (Vatican City State)")
  HN: 'america settentrionale', // "Republic of Honduras")
  HK: 'asia', // "Hong Kong Special Administrative Region of China")
  HU: 'europa', // "Hungary")
  IS: 'europa', // "Republic of Iceland")
  IN: 'asia', // "Republic of India")
  ID: 'asia', // "Republic of Indonesia")
  IR: 'asia', // "Islamic Republic of Iran")
  IQ: 'asia', // "Republic of Iraq")
  IE: 'europa', // "Ireland")
  IM: 'europa', // "Isle of Man")
  IL: 'asia', // "State of Israel")
  IT: 'europa', // "Italian Republic")
  JM: 'america settentrionale', // "Jamaica")
  JP: 'asia', // "Japan")
  JE: 'europa', // "Bailiwick of Jersey")
  JO: 'asia', // "Hashemite Kingdom of Jordan")
  KZ: 'asia', // "Republic of Kazakhstan")
  KE: 'africa', // "Republic of Kenya")
  KI: 'oceania', // "Republic of Kiribati")
  KP: 'asia', // "Democratic People's Republic of Korea")
  KR: 'asia', // "Republic of Korea")
  KW: 'asia', // "State of Kuwait")
  KG: 'asia', // "Kyrgyz Republic")
  LA: 'asia', // "Lao People's Democratic Republic")
  LV: 'europa', // "Republic of Latvia")
  LB: 'asia', // "Lebanese Republic")
  LS: 'africa', // "Kingdom of Lesotho")
  LR: 'africa', // "Republic of Liberia")
  LY: 'africa', // "Libya")
  LI: 'europa', // "Principality of Liechtenstein")
  LT: 'europa', // "Republic of Lithuania")
  LU: 'europa', // "Grand Duchy of Luxembourg")
  MO: 'asia', // "Macao Special Administrative Region of China")
  MK: 'europa', // "Republic of Macedonia")
  MG: 'africa', // "Republic of Madagascar")
  MW: 'africa', // "Republic of Malawi")
  MY: 'asia', // "Malaysia")
  MV: 'asia', // "Republic of Maldives")
  ML: 'africa', // "Republic of Mali")
  MT: 'europa', // "Republic of Malta")
  MH: 'oceania', // "Republic of the Marshall Islands")
  MQ: 'america settentrionale', // "Martinique")
  MR: 'africa', // "Islamic Republic of Mauritania")
  MU: 'africa', // "Republic of Mauritius")
  YT: 'africa', // "Mayotte")
  MX: 'america settentrionale', // "United Mexican States")
  FM: 'oceania', // "Federated States of Micronesia")
  MD: 'europa', // "Republic of Moldova")
  MC: 'europa', // "Principality of Monaco")
  MN: 'asia', // "Mongolia")
  ME: 'europa', // "Montenegro")
  MS: 'america settentrionale', // "Montserrat")
  MA: 'africa', // "Kingdom of Morocco")
  MZ: 'africa', // "Republic of Mozambique")
  MM: 'asia', // "Republic of the Union of Myanmar")
  NA: 'africa', // "Republic of Namibia")
  NR: 'oceania', // "Republic of Nauru")
  NP: 'asia', // "Federal Democratic Republic of Nepal")
  NL: 'europa', // "Kingdom of the Netherlands")
  NC: 'oceania', // "New Caledonia")
  NZ: 'oceania', // "New Zealand")
  NI: 'america settentrionale', // "Republic of Nicaragua")
  NE: 'africa', // "Republic of Niger")
  NG: 'africa', // "Federal Republic of Nigeria")
  NU: 'oceania', // "Niue")
  NF: 'oceania', // "Norfolk Island")
  MP: 'oceania', // "Commonwealth of the Northern Mariana Islands")
  NO: 'europa', // "Kingdom of Norway")
  OM: 'asia', // "Sultanate of Oman")
  PK: 'asia', // "Islamic Republic of Pakistan")
  PW: 'oceania', // "Republic of Palau")
  PS: 'asia', // "Occupied Palestinian Territory")
  PA: 'america settentrionale', // "Republic of Panama")
  PG: 'oceania', // "Independent State of Papua New Guinea")
  PY: 'america meridionale', // "Republic of Paraguay")
  PE: 'america meridionale', // "Republic of Peru")
  PH: 'asia', // "Republic of the Philippines")
  PN: 'oceania', // "Pitcairn Islands")
  PL: 'europa', // "Republic of Poland")
  PT: 'europa', // "Portuguese Republic")
  PR: 'america settentrionale', // "Commonwealth of Puerto Rico")
  QA: 'asia', // "State of Qatar")
  RE: 'africa', // "Réunion")
  RO: 'europa', // "Romania")
  RU: 'europa', // "Russian Federation")
  RW: 'africa', // "Republic of Rwanda")
  BL: 'america settentrionale', // "Saint Barthélemy")
  SH: 'africa', // '654'
  KN: 'america settentrionale', // "Federation of Saint Kitts and Nevis")
  LC: 'america settentrionale', // "Saint Lucia")
  MF: 'america settentrionale', // "Saint Martin (French part)")
  PM: 'america settentrionale', // "Saint Pierre and Miquelon")
  VC: 'america settentrionale', // "Saint Vincent and the Grenadines")
  WS: 'oceania', // "Independent State of Samoa")
  SM: 'europa', // "Republic of San Marino")
  ST: 'africa', // "Democratic Republic of Sao Tome and Principe")
  SA: 'asia', // "Kingdom of Saudi Arabia")
  SN: 'africa', // "Republic of Senegal")
  RS: 'europa', // "Republic of Serbia")
  SC: 'africa', // "Republic of Seychelles")
  SL: 'africa', // "Republic of Sierra Leone")
  SG: 'asia', // "Republic of Singapore")
  SX: 'america settentrionale', // "Sint Maarten (Dutch part)")
  SK: 'europa', // "Slovakia (Slovak Republic)")
  SI: 'europa', // "Republic of Slovenia")
  SB: 'oceania', // "Solomon Islands")
  SO: 'africa', // "Somali Republic")
  ZA: 'africa', // "Republic of South africa")
  GS: 'Antarctica', // "South Georgia and the South Sandwich Islands")
  SS: 'africa', // "Republic of South Sudan")
  ES: 'europa', // "Kingdom of Spain")
  LK: 'asia', // "Democratic Socialist Republic of Sri Lanka")
  SD: 'africa', // "Republic of Sudan")
  SR: 'america meridionale', // "Republic of Suriname")
  SJ: 'europa', // "Svalbard & Jan Mayen Islands")
  SZ: 'africa', // "Kingdom of Swaziland")
  SE: 'europa', // "Kingdom of Sweden")
  CH: 'europa', // "Swiss Confederation")
  SY: 'asia', // "Syrian Arab Republic")
  TW: 'asia', // "Taiwan
  TJ: 'asia', // "Republic of Tajikistan")
  TZ: 'africa', // "United Republic of Tanzania")
  TH: 'asia', // "Kingdom of Thailand")
  TL: 'asia', // "Democratic Republic of Timor-Leste")
  TG: 'africa', // "Togolese Republic")
  TK: 'oceania', // "Tokelau")
  TO: 'oceania', // "Kingdom of Tonga")
  TT: 'america settentrionale', // "Republic of Trinidad and Tobago")
  TN: 'africa', // "Tunisian Republic")
  TR: 'europa', // "Republic of Turkey")
  TM: 'asia', // "Turkmenistan")
  TC: 'america settentrionale', // "Turks and Caicos Islands")
  TV: 'oceania', // "Tuvalu")
  UG: 'africa', // "Republic of Uganda")
  UA: 'europa', // "Ukraine")
  AE: 'asia', // "United Arab Emirates")
  GB: 'europa', // "United Kingdom of Great Britain & Northern Ireland")
  US: 'america settentrionale', // "United States of America")
  UM: 'oceania', // "United States Minor Outlying Islands")
  VI: 'america settentrionale', // "United States Virgin Islands")
  UY: 'america meridionale', // "Eastern Republic of Uruguay")
  UZ: 'asia', // "Republic of Uzbekistan")
  VU: 'oceania', // "Republic of Vanuatu")
  VE: 'america meridionale', // "Bolivarian Republic of Venezuela")
  VN: 'asia', // "Socialist Republic of Vietnam")
  WF: 'oceania', // "Wallis and Futuna")
  EH: 'africa', // "Western Sahara")
  YE: 'asia', // "Yemen")
  ZM: 'africa', // "Republic of Zambia")
  ZW: 'africa'// "Republic of Zimbabwe");
}
